taws/Controllers/TestCaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using taws.Models;
using tawsLibrary;

namespace taws.Controllers
{
    public class TestCaseController : Controller
    {
        // GET: TestCase
        public ActionResult index()
        {
            return View();
        }
        public ActionResult Insert()
        {
            return View();
        }

        public ActionResult Insert2(TestCaseProperty testCase)
        {
            var fileIo = new FileIo();

            //テストケース登録日時取得
            string testDateTime = DateTime.Now.ToString("yyyyMMdd_HHmmss");

            //テストケースファイル保存
            string uploadFileSavePath = fileIo.SaveTestCaseFiles(testCase.testCaseFile, testDateTime);

            //ファイルからテストケース取得
            testCase.testElemList = new FileIo().TestCaseFromUploadFile(uploadFileSavePath, testCase.testCaseFile);

            //DataBaseにInsertする
            var testCaseFac = new TestCaseFactory();
            testCase.resultMsg = testCaseFac.insertTestCase(testCase);

            return View("complete", testCase);
        }
    }
}

taws/Controllers/tawsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Windows;
using System.Threading;
using System.Transactions;
using System.Configuration;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.IE;
using Npgsql;
using taws.Models;
using taws.Validate;
using tawsCommons;
using tawsLibrary;

namespace taws.Controllers
{
    public class tawsController : Controller
    {
        public ActionResult Index(TestProperty prop)
        {
            //データベースからテストケースを取得
            prop.testCaseList = new DataBaseIo().ExeReader<TestCase>("select * from test_case_t");

            return View(prop);
        }

        public ActionResult TestAction(TestProperty prop)
        {
            //Validation
            new tawsValidate().Validate(prop);
            if (prop.validationMsg.Count != 0)
            {
                //データベースからテストケースを取得
                prop.testCaseList = new DataBaseIo().ExeReader<TestCase>("select * from test_case_t");

                return View("Index", prop);
            }

            //var browerName = ConfigurationManager.AppSettings["BrowserName"];
            var browerName = prop.testBrowser;

            //テスト実施日時取得
            prop.testDateTime = DateTime.Now.ToString("yyyyMMdd_HHmmss");

            //エビデンス用ディレクトリ作成
            var fileIo = new FileIo();
            prop.evidenceSavePath = fileIo.CreateEvidencesDirectory(prop);
            //テストケースファイル保存
            prop.uploadFileSavePath = fileIo.SaveTestCaseFiles(prop.testCaseFile, prop.testDateTime);

            //URL設定(configから)
            //var prop.testURL = $"{ConfigurationManager.AppSettings["Url"]}member";

            //ウィンドウ表示位置設定
            prop.positionX = 0;
            prop.positionY = 0;

            //スクリーンサイズ取得
            if (prop.testDevice == "pc")
            {
                prop.screenWidth = Convert.ToInt32(ConfigurationManager.AppSettings["BrowerWidth"]);
                prop.screenHeight = Convert.ToInt32(ConfigurationManager.AppSettings["BrowerHeight"]);
            }
            else if (prop.testDevice == "sp_iphone")
            {
                prop.screenWidth = Convert.ToInt32(ConfigurationManager.AppSettings["BrowerWidthiPhone"]);
                prop.screenHeight = Convert.ToInt32(ConfigurationManager.AppSettings["BrowerHeightiPhone"]);
            }
            else if (prop.testDevice == "sp_android")
            {
                prop.screenWidth = Convert.ToInt32(ConfigurationManager.AppSettings["BrowerWidthAndroid"]);
                prop.screenHeight = Convert.ToInt32(ConfigurationManager.AppSettings["BrowerHeightAndroid"]);
            }


            //テスト実施---------------------------------------

            var excuteTest = new TestExecute();

            //Google Chromeのテスト
            if (browerName == "chrome")
            {
                //Web Driverの設定
                var option = new ChromeOptions();
                if (prop.testDevice == "sp_iphone")
                {
                    option.AddArgument($"--user-agent=\"{ ConfigurationManager.AppSettings["UserAgentiPhone"] }\"");
                }
                else if (prop.testDevice == "sp_android")
                {
                    option.AddArgument($"--user-agent=\"{ ConfigurationManager.AppSettings["UserAgentAndroid"] }\"");
                }

                excuteTest.ExeTest<ChromeDriver>(new ChromeDriver(option), prop);
            }
            //FireFoxのテスト
            else if (browerName == "firefox")
            {
                //Web Driverの設定
                var option = new FirefoxOptions();
                if (prop.testDevice == "sp_iphone")
                {
                    option.SetPreference("general.useragent.override", ConfigurationManager.AppSettings["UserAgentiPhone"]);
                }
                else if (prop.testDevice == "sp_android")
                {
                    option.SetPreference("general.useragent.override", ConfigurationManager.AppSettings["UserAgentAndroid"]);
                }
                //Proxyの設定
                if (Convert.ToBoolean(ConfigurationManager.AppSettings["SetProxy"]))
                {
                    var fireComm = new FireFoxTestCommons();
                    option = fireComm.SetProxy(option, ConfigurationManager.AppSettings["NonProxyString"]);
                }

                excuteTest.ExeTest<FirefoxDriver>(new FirefoxDriver(option), prop);
            }
            //Edgeのテスト
            else if (browerName == "edge")
            {
                excuteTest.ExeTest<EdgeDriver>(new EdgeDriver(), prop);
            }

            prop.resultMsg = $@"{ prop.evidenceSavePath } にテスト結果が保存されました。";

            return View("complete", prop);
        }

        public ActionResult complete()
        {
            return View("complete");
        }
    }
}

taws/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Test automatic of web site</title>
    @Styles.Render("~/Content")
    @*@Scripts.Render("~/bundles/modernizr")*@
    @Scripts.Render("~/Scripts")
    
    <link rel="stylesheet" type="text/css" href="~/Content/main.css">
    <script type="text/javascript" src="~/Scripts/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.js"></script>
</head>
<body>
    <div class="navbar navbar-dark bg-dark">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Home", "Index", "taws", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("新規登録", "Insert", "TestCase", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("新規登録", "Insert", "TestCase")</li>
                    <li>@Html.ActionLink("更新", "Update", "TestCase")</li>
                    <li>@Html.ActionLink("削除", "Delete", "TestCase")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Test automatic of web site</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>